import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { FileText, ArrowLeft, Download, Copy, Check, Users, Target, ListChecks, Calendar, ExternalLink, Save } from 'lucide-react';

const MeetingNotesTool = ({ onBack }) => {
    const [title, setTitle] = useState('');
    const [date, setDate] = useState(new Date().toISOString().split('T')[0]);
    const [attendees, setAttendees] = useState('');
    const [agenda, setAgenda] = useState('');
    const [decisions, setDecisions] = useState('');
    const [actionItems, setActionItems] = useState('');
    const [notes, setNotes] = useState('');
    const [copied, setCopied] = useState(false);
    const [saved, setSaved] = useState(false);

    const generateMarkdown = () => {
        return `# Meeting: ${title || 'Untitled Meeting'}
**Date:** ${date}
**Attendees:** ${attendees || 'None specified'}

---

## 📋 Agenda
${agenda || '*No agenda specified*'}

---

## 🔴 Key Decisions
${decisions || '*No decisions recorded*'}

---

## ✅ Action Items
${actionItems || '*No action items assigned*'}

---

## 📝 General Notes
${notes || '*No additional notes*'}

---
*Generated by Tools for Work Meeting Architect*`;
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(generateMarkdown());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownload = () => {
        const element = document.createElement("a");
        const file = new Blob([generateMarkdown()], { type: 'text/markdown' });
        element.href = URL.createObjectURL(file);
        const fileName = (title || 'Meeting_Notes').replace(/\s+/g, '_') + '.md';
        element.download = fileName;
        document.body.appendChild(element);
        element.click();
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
    };

    return (
        <div className="container animate-fade-in" style={{ paddingTop: '20px', paddingBottom: '80px' }}>
            <button onClick={onBack} className="button-secondary" style={{ marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <ArrowLeft size={18} /> Back
            </button>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }} className="responsive-grid">
                {/* Editor Panel */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                    <div className="glass-panel" style={{ padding: '32px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '32px' }}>
                            <FileText size={24} className="text-blue-400" />
                            <h2 style={{ fontSize: '1.5rem', fontWeight: 800 }}>Meeting Architect</h2>
                        </div>

                        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
                            <div className="input-group">
                                <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 700 }}>MEETING TITLE</label>
                                <input
                                    type="text"
                                    value={title}
                                    onChange={(e) => setTitle(e.target.value)}
                                    placeholder="Q1 Strategic Review..."
                                    style={{ width: '100%', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '12px 16px', color: 'white', outline: 'none' }}
                                />
                            </div>

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
                                <div className="input-group">
                                    <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 700 }}>DATE</label>
                                    <div style={{ position: 'relative' }}>
                                        <Calendar size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
                                        <input
                                            type="date"
                                            value={date}
                                            onChange={(e) => setDate(e.target.value)}
                                            style={{ width: '100%', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '12px 16px 12px 40px', color: 'white', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                                <div className="input-group">
                                    <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 700 }}>ATTENDEES</label>
                                    <div style={{ position: 'relative' }}>
                                        <Users size={18} style={{ position: 'absolute', left: '12px', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
                                        <input
                                            type="text"
                                            value={attendees}
                                            onChange={(e) => setAttendees(e.target.value)}
                                            placeholder="Alex, Sarah, Mike..."
                                            style={{ width: '100%', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '12px 16px 12px 40px', color: 'white', outline: 'none' }}
                                        />
                                    </div>
                                </div>
                            </div>

                            <div className="input-group">
                                <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 700 }}>AGENDA</label>
                                <textarea
                                    value={agenda}
                                    onChange={(e) => setAgenda(e.target.value)}
                                    placeholder="- Review performance&#10;- Discuss blockers&#10;- Plan next sprints"
                                    style={{ width: '100%', height: '100px', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '12px 16px', color: 'white', outline: 'none', resize: 'none', fontFamily: 'monospace' }}
                                />
                            </div>

                            <div className="input-group">
                                <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: '#10b981', fontWeight: 700 }}>KEY DECISIONS</label>
                                <textarea
                                    value={decisions}
                                    onChange={(e) => setDecisions(e.target.value)}
                                    placeholder="- Budget approved for Q2&#10;- Remote-first policy confirmed"
                                    style={{ width: '100%', height: '100px', background: 'rgba(16, 185, 129, 0.05)', border: '1px solid rgba(16, 185, 129, 0.2)', borderRadius: '12px', padding: '12px 16px', color: 'white', outline: 'none', resize: 'none', fontFamily: 'monospace' }}
                                />
                            </div>

                            <div className="input-group">
                                <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: '#818cf8', fontWeight: 700 }}>ACTION ITEMS</label>
                                <textarea
                                    value={actionItems}
                                    onChange={(e) => setActionItems(e.target.value)}
                                    placeholder="- [ ] @Sarah: Update roadmap&#10;- [ ] @Alex: Research API endpoints"
                                    style={{ width: '100%', height: '100px', background: 'rgba(129, 140, 248, 0.05)', border: '1px solid rgba(129, 140, 248, 0.2)', borderRadius: '12px', padding: '12px 16px', color: 'white', outline: 'none', resize: 'none', fontFamily: 'monospace' }}
                                />
                            </div>

                            <div className="input-group">
                                <label style={{ display: 'block', marginBottom: '8px', fontSize: '0.85rem', color: 'var(--text-muted)', fontWeight: 700 }}>GENERAL NOTES</label>
                                <textarea
                                    value={notes}
                                    onChange={(e) => setNotes(e.target.value)}
                                    placeholder="Enter additional details here..."
                                    style={{ width: '100%', height: '150px', background: 'rgba(255,255,255,0.05)', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '12px 16px', color: 'white', outline: 'none', resize: 'none', fontFamily: 'sans-serif' }}
                                />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Preview Panel */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', position: 'sticky', top: '100px', height: 'fit-content' }}>
                    <div className="glass-panel" style={{ padding: '32px', display: 'flex', flexDirection: 'column', height: '800px', background: 'rgba(15, 23, 42, 0.6)' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                                <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#10b981' }} />
                                <span style={{ fontSize: '0.8rem', fontWeight: 800, color: 'var(--text-muted)' }}>MARKDOWN PREVIEW</span>
                            </div>
                            <div style={{ display: 'flex', gap: '12px' }}>
                                <button onClick={handleCopy} className="button-secondary" style={{ padding: '8px 16px', fontSize: '0.8rem' }}>
                                    {copied ? <Check size={16} /> : <Copy size={16} />} {copied ? 'Copied' : 'Copy MD'}
                                </button>
                                <button onClick={handleDownload} className="button-primary" style={{ padding: '8px 16px', fontSize: '0.8rem' }}>
                                    <Download size={16} /> Save .md
                                </button>
                            </div>
                        </div>

                        <div style={{ flexGrow: 1, background: 'rgba(0,0,0,0.2)', borderRadius: '16px', padding: '32px', overflowY: 'auto', border: '1px solid var(--glass-border)' }}>
                            <pre style={{ margin: 0, whiteSpace: 'pre-wrap', fontFamily: '"Fira Code", monospace', fontSize: '0.9rem', color: '#94a3b8', lineHeight: 1.6 }}>
                                {generateMarkdown()}
                            </pre>
                        </div>

                        <div style={{ marginTop: '24px', padding: '20px', background: 'rgba(59, 130, 246, 0.05)', borderRadius: '12px', border: '1px solid rgba(59, 130, 246, 0.1)' }}>
                            <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
                                <Target size={20} className="text-blue-400" />
                                <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', margin: 0 }}>
                                    Your notes are formatted in <strong>GitHub Flavored Markdown</strong>, perfect for pasting into Notion, GitHub Discussions, or Slack.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default MeetingNotesTool;
